"""strip_vcs_from_lock.py removes VCS stanzas for pip --require-hashes."""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location(
    "strip_vcs_from_lock",
    _ROOT / "scripts" / "strip_vcs_from_lock.py",
)
assert _spec and _spec.loader
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
strip_vcs_from_lock = _mod.strip_vcs_from_lock


def test_strip_removes_am4_and_warning() -> None:
    sample = """#
# This file is autogenerated
#
# WARNING: pip install will require the following package to be hashed.
# Consider using a hashable URL
am4 @ git+https://github.com/saqibj/am4.git@deadbeef
    # via -r requirements.in
foo==1.0.0 \\
    --hash=sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    # via -r requirements.in
"""
    out = strip_vcs_from_lock(sample)
    assert "am4 @" not in out
    assert "WARNING" not in out
    assert "foo==1.0.0" in out
    assert "sha256:aa" in out


def test_repo_lock_strips_cleanly() -> None:
    lock_path = Path(__file__).resolve().parents[1] / "requirements.lock"
    if not lock_path.is_file():
        pytest.skip("requirements.lock not present")
    text = lock_path.read_text(encoding="utf-8")
    out = strip_vcs_from_lock(text)
    assert "am4 @" not in out
    assert "annotated-doc==" in out
